CREATE TABLE "USUARIO" (
  "ID_USER" NUMBER(9) NOT NULL,
  "NOME" VARCHAR2(60) NOT NULL,
  "DATA_NASCIMENTO" DATE,
  "GENERO" VARCHAR(20),
  "PREMIUM" NUMBER(1) NOT NULL,
  PRIMARY KEY ("ID_USER")
);

CREATE TABLE "SEGUIDORES" (
  "ID_USER" NUMBER(9) NOT NULL,
  "ID_USER_SEGUINDO" NUMBER(9) NOT NULL,
  PRIMARY KEY ("ID_USER", "ID_USER_SEGUINDO"),
  CONSTRAINT "FK_SEGUIDORES.ID_USER"
    FOREIGN KEY ("ID_USER")
      REFERENCES "USUARIO"("ID_USER"),
  CONSTRAINT "FK_SEGUIDORES.ID_USER_SEGUINDO"
    FOREIGN KEY ("ID_USER_SEGUINDO")
      REFERENCES "USUARIO"("ID_USER")
);

CREATE TABLE "OUVINTE" (
  "ID_USER" NUMBER(9) NOT NULL,
  "ID_OUVINTE" NUMBER(9) NOT NULL,
  PRIMARY KEY ("ID_OUVINTE")
);

CREATE TABLE "PLAYLIST" (
  "ID_PLAYLIST" NUMBER(9) NOT NULL,
  "ID_OUVINTE" NUMBER(9) NOT NULL,
  "NOME" VARCHAR2(60) NOT NULL,
  PRIMARY KEY ("ID_PLAYLIST"),
  CONSTRAINT "FK_PLAYLIST.ID_OUVINTE"
    FOREIGN KEY ("ID_OUVINTE")
      REFERENCES "OUVINTE"("ID_OUVINTE")
);

CREATE TABLE "ARTISTA" (
  "ID_USER" NUMBER(9) NOT NULL,
  "ID_ARTISTA" NUMBER(9) NOT NULL,
  "BIO" VARCHAR2(500),
  "AVALIACAO" NUMBER(1),
  PRIMARY KEY ("ID_ARTISTA")
);

CREATE TABLE "ALBUM" (
  "ID_ALBUM" NUMBER(9) NOT NULL,
  "ID_ARTISTA" NUMBER(9) NOT NULL,
  "NOME" VARCHAR2(200) NOT NULL,
  "AVALIACAO" NUMBER(1),
  PRIMARY KEY ("ID_ALBUM"),
  CONSTRAINT "FK_ALBUM.ID_ARTISTA"
    FOREIGN KEY ("ID_ARTISTA")
      REFERENCES "ARTISTA"("ID_ARTISTA")
);

CREATE TABLE "MUSICA" (
  "ID_MUSICA" NUMBER(9) NOT NULL,
  "ID_ALBUM" NUMBER(9) NOT NULL,
  "NOME" VARCHAR2(200),
  "AVALIACAO" NUMBER(1),
  "DURACAO" NUMBER(3) NOT NULL,
  "CURTIDAS" NUMBER(9) ,
  PRIMARY KEY ("ID_MUSICA"),
  CONSTRAINT "FK_MUSICA.ID_ALBUM"
    FOREIGN KEY ("ID_ALBUM")
      REFERENCES "ALBUM"("ID_ALBUM")
);

CREATE TABLE "LISTADEMUSICAS" (
  "ID_PLAYLIST" NUMBER(9) NOT NULL,
  "ID_MUSICA" NUMBER(9) NOT NULL,
  PRIMARY KEY ("ID_PLAYLIST", "ID_MUSICA"),
  CONSTRAINT "FK_LISTADEMUSICAS.ID_PLAYLIST"
    FOREIGN KEY ("ID_PLAYLIST")
      REFERENCES "PLAYLIST"("ID_PLAYLIST"),
  CONSTRAINT "FK_LISTADEMUSICAS.ID_MUSICA"
    FOREIGN KEY ("ID_MUSICA")
      REFERENCES "MUSICA"("ID_MUSICA")
);

